// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpRGuFEAmTaiU51Dw1y51oFQY0wslq0bE',
    appId: '1:283633165905:web:667605658ae76af9cdba70',
    messagingSenderId: '283633165905',
    projectId: 'finance-app-4a537',
    authDomain: 'finance-app-4a537.firebaseapp.com',
    storageBucket: 'finance-app-4a537.firebasestorage.app',
    measurementId: 'G-7MZEWPX941',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFQSqyXRyRt-79KQS1VmO64Jf9nkCwPxA',
    appId: '1:283633165905:android:ae52554bdcf77adecdba70',
    messagingSenderId: '283633165905',
    projectId: 'finance-app-4a537',
    storageBucket: 'finance-app-4a537.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxTS8O6LUsJa6kMHsifFBbXtfBsb6Eiy4',
    appId: '1:283633165905:ios:25f14e9d75ad4d0fcdba70',
    messagingSenderId: '283633165905',
    projectId: 'finance-app-4a537',
    storageBucket: 'finance-app-4a537.firebasestorage.app',
    iosBundleId: 'com.example.verygoodcore.finance-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxTS8O6LUsJa6kMHsifFBbXtfBsb6Eiy4',
    appId: '1:283633165905:ios:168ed056e706831bcdba70',
    messagingSenderId: '283633165905',
    projectId: 'finance-app-4a537',
    storageBucket: 'finance-app-4a537.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpRGuFEAmTaiU51Dw1y51oFQY0wslq0bE',
    appId: '1:283633165905:web:b844c16738bba636cdba70',
    messagingSenderId: '283633165905',
    projectId: 'finance-app-4a537',
    authDomain: 'finance-app-4a537.firebaseapp.com',
    storageBucket: 'finance-app-4a537.firebasestorage.app',
    measurementId: 'G-ZXYW441S4L',
  );
}