name: finance_app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      flutter_version: ${{ steps.read_fvm.outputs.version }}
      license_check_needed: ${{ steps.changes.outputs.license }}
    steps:
      - uses: actions/checkout@v6
      - id: read_fvm
        name: Extract Version from .fvmrc
        run: |
          VERSION=$(jq -r .flutter .fvmrc)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            license:
              - "pubspec.yaml"
              - ".github/workflows/license_check.yaml"

  deploy_preview:
    name: Deploy Preview
    needs: [setup]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.setup.outputs.flutter_version }}
      - run: flutter pub get
      - run: pushd packages/feature_flags_repository && flutter pub get && popd
      - run: flutter build web --wasm --target lib/main_development.dart
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: finance-app-4a537

  